### ISSUE TITLE
Neo4j server startup not running

### ISSUE THREAD

**Issue by Vishnubala95** [kbastani/graphify#32]
Hi,

Can anyone help me

Neo4j server which was previously working, got this error and server is not getting started once i copy the graphify jar into the plugins directory. And where is the server properties in the conf file?

This is the log generated....

2018-03-21 16:38:01.431+0000 INFO  ======== Neo4j 3.3.4 ========
2018-03-21 16:38:01.494+0000 INFO  Starting...
2018-03-21 16:38:03.431+0000 INFO  Bolt enabled on 127.0.0.1:7687.
2018-03-21 16:38:03.469+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@5e21e98f' was successfully initialized, but failed to start. Please see the attached cause exception "null". Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@5e21e98f' was successfully initialized, but failed to start. Please see the attached cause exception "null".
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@5e21e98f' was successfully initialized, but failed to start. Please see the attached cause exception "null".
	at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:68)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:220)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:111)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:79)
	at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:32)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@5e21e98f' was successfully initialized, but failed to start. Please see the attached cause exception "null".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:466)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:212)
	... 3 more
Caused by: java.lang.RuntimeException: Error starting org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory, /home/jarvis/Documents/neo4j-community-3.3.4/data/databases/graph.db
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:211)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:126)
	at org.neo4j.server.CommunityNeoServer.lambda$static$0(CommunityNeoServer.java:58)
	at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:88)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:445)
	... 5 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.extension.KernelExtensions@2663e964' failed to initialize. Please see the attached cause exception "null".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:427)
	at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:62)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:98)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:207)
	... 9 more
Caused by: java.lang.AbstractMethodError
	at org.neo4j.kernel.extension.KernelExtensions.newInstance(KernelExtensions.java:78)
	at org.neo4j.kernel.extension.KernelExtensions.init(KernelExtensions.java:61)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:406)
	... 12 more
2018-03-21 16:38:03.479+0000 INFO  Neo4j Server shutdown initiated by request

**Comment by alperhankendi** [comment]
same issue

**Comment by bingchengcool** [comment]
same issue

**Comment by sbala89** [comment]
same issue
